name: Build

on:
  push:
    branches:
      - main
      - "dev/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@ca041f971d66735f3e5ff1e21cc13e2d51e7e535 # v1.233.0
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Lint
        run: bundle exec rake standard

  integration_test:
    runs-on: ubuntu-latest

    needs: test

    strategy:
      matrix:
        ruby_version: ["3.3"]
        redmine_branch_name: ["master", "6.0-stable"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@ca041f971d66735f3e5ff1e21cc13e2d51e7e535 # v1.233.0
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Set up test
        run: bundle exec rake test:prepare_integration
        env:
          RUBY_VERSION: ${{ matrix.ruby_version }}
          REDMINE_BRANCH_NAME: ${{ matrix.redmine_branch_name }}

      - name: Run integration tests
        run: bundle exec rake test:integration
        env:
          RUBY_VERSION: ${{ matrix.ruby_version }}
          REDMINE_BRANCH_NAME: ${{ matrix.redmine_branch_name }}
