name: Build

on:
  push:
    branches:
      - main
      - "dev/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Lint
        run: bundle exec rake standard

  integration_test:
    runs-on: ubuntu-latest

    needs: test

    strategy:
      matrix:
        include:
          - ruby_version: "3.3"
            redmine_branch_name: "master"
          - ruby_version: "3.2"
            redmine_branch_name: "5.1-stable"

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Set up test
        run: bundle exec rake test:prepare_integration
        env:
          RUBY_VERSION: ${{ matrix.ruby_version }}
          REDMINE_BRANCH_NAME: ${{ matrix.redmine_branch_name }}

      - name: Run integration tests
        run: bundle exec rake test:integration
        env:
          RUBY_VERSION: ${{ matrix.ruby_version }}
          REDMINE_BRANCH_NAME: ${{ matrix.redmine_branch_name }}
